before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  dir: cmd/pping
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
